[package]
name = "dengjen-espeak-rs"
version.workspace = true
license = "GPL-3.0-or-later"
description = "Safe Rust bindings to espeak-ng"
keywords = ["espeak-ng", "audio", "tts", "speech", "rodio"]
repository = "https://github.com/ZirekHQ/dengjen-piper-rs"
edition = "2024"

[dependencies]
# Local crates
espeak-rs-sys = { path = "../espeak-rs-sys", package = "dengjen-espeak-rs-sys", version = "0.2.0" }


[features]
default = ["compile-espeak-intonations"]
compile-espeak-intonations = ["espeak-rs-sys/compile-espeak-intonations"]
