repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-yaml

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.28.0
    hooks:
      - id: zizmor

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: ["--workspace", "--lib", "--bins", "--", "-D", "warnings"]
