[workspace]
members = ["crates/espeak-rs", "crates/piper-core", "crates/stub-adapter", "crates/fs-voice-repo", "crates/ort-adapter", "crates/espeak-rs-adapter"]
resolver = "1"

[workspace.package]
version = "0.2.0"

[package]
name = "dengjen-piper-rs"
version.workspace = true
edition = "2024"
license = "GPL-3.0-or-later"
description = "Use piper TTS models in Rust"
repository = "https://github.com/ZirekHQ/dengjen-piper-rs"

[dependencies]
espeak-rs = { path = "crates/espeak-rs", package = "dengjen-espeak-rs", version = "0.2.0", default-features = false, optional = true }
ndarray = "0.16.1"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.89"
ort = { version = "=2.0.0-rc.12" }
espeak-ng = { version = "0.1.3", optional = true }
unicode-normalization = "0.1"

[dev-dependencies]
rodio = "0.22"
piper-core = { path = "crates/piper-core", package = "dengjen-piper-core" }
fs-voice-repo = { path = "crates/fs-voice-repo", package = "dengjen-fs-voice-repo" }
stub-adapter = { path = "crates/stub-adapter", package = "dengjen-stub-adapter" }
ort-adapter = { path = "crates/ort-adapter", package = "dengjen-ort-adapter" }
espeak-rs-adapter = { path = "crates/espeak-rs-adapter", package = "dengjen-espeak-rs-adapter" }
tempfile = "3.13"

[features]
default = ["espeak-rs", "compile-espeak-intonations"]
espeak-rs = ["dep:espeak-rs"]
espeak-ng = ["dep:espeak-ng"]
compile-espeak-intonations = ["espeak-rs/compile-espeak-intonations"]
