[package]
name = "dengjen-espeak-rs-sys"
version = "0.2.0"
edition = "2024"
description = "Rust bindings to espeak-ng"
license = "GPL-3.0-or-later"
repository = "https://github.com/ZirekHQ/dengjen-piper-rs"

include = [
    "bundled/espeak-ng.tar.xz",
    "src/*.rs",
    "build.rs",
    "wrapper.h",
]

[build-dependencies]
bindgen = "0.72.1"
cmake = "0.1"
glob = "0.3.1"
lzma-rs = "0.3.0"
tar = "0.4.46"

[dev-dependencies]
bindgen = "0.72.1"
cmake = "0.1"
glob = "0.3.1"
lzma-rs = "0.3.0"
tar = "0.4.46"

[features]
default = []
compile-espeak-intonations = []

[[test]]
name = "build_script_unit_tests"
path = "build.rs"
